### ISSUE TITLE
Add choices for local identifiers in deposits

### ISSUE THREAD

**Issue by sebastiendeleze** [rero/sonar-ui#124]
* In deposit process, add choices for local identifiers (PMID, ...).
* Display identifiers in the public/pro detailed views.

**Comment by sebastiendeleze** [comment]
@pronguen Can you please complete the specifications for this issue?

**Comment by pronguen** [comment]
# What we would like in the deposit editor

(The codes are indicated, in the UI we want display label that are slightly different.)

bf:Doi
pmid
bf:Isbn
~-~-~
bf:AudioIssueNumber
bf:Ean
bf:Gtin14Number
bf:Identifier
bf:Isan
bf:Ismn
bf:Isrc
bf:Issn
bf:Local
bf:IssnL
bf:MatrixNumber
bf:MusicDistributorNumber
bf:MusicPlate
bf:MusicPublisherNumber
bf:PublisherNumber
bf:Upc
bf:Urn
bf:VideoRecordingNumber
uri
bf:ReportNumber
bf:Strn

# What we would like as official data structure (and in the document editor)

bf:AudioIssueNumber
bf:Doi
bf:Ean
bf:Gtin14Number
bf:Identifier
bf:Isan
bf:Isbn
bf:Ismn
bf:Isrc
bf:Issn
bf:Local
bf:IssnL
bf:MatrixNumber
bf:MusicDistributorNumber
bf:MusicPlate
bf:MusicPublisherNumber
bf:PublisherNumber
bf:Upc
bf:Urn
bf:VideoRecordingNumber
uri
bf:ReportNumber
bf:Strn

# How the PMID should be stored

```
"identifiedBy": [{
		"type": "bf:Local",
		"source": "PMID",
		"value": "327171"
	}
]
```

# Regular expressions for some of the ID types (for now a nice to have)

bf:Doi regex `^10\..+\/.+$`
pmid regex `^[1-3]\d{7}|[1-9]\d{0,6}$`
bf:Isbn regex `^(97(8|9))?\d{9}(\d|X)$`
uri regex `^https?:\/\/.+\..+$`

**Comment by sebastiendeleze** [comment]
I'm not sure about the regex for `pmid`. For example, `3` value pass the validation.. Are you sure about that?
