### ISSUE TITLE
Submission process changes

### ISSUE THREAD

**Issue by sebastiendeleze** [rero/sonar-ui#62]
* Classification is not mandatory.
* Publication date can be only a year.
* Document date can be a year or a full date.
* Affiliations can be empty.
* Check list of document types.

**Comment by sebastiendeleze** [comment]
Full list of document types is implemented in PR #206.

**Comment by sebastiendeleze** [comment]
@pronguen In my last comment, I wrote:

* Publication date can be only a year

But I don't remember why.. That means property *numberingYear* of field *publication* could be a year or a full date? Sorry..

**Comment by pronguen** [comment]
The field numberingYear is structured in RERO DOC (even if it is not constrained). It is used only to situate an article inside a journal. See example below, subfield "g". Typically, value "Mai" will be lost, because it was entered incorrectly...

```
<datafield tag="773" ind1=" " ind2=" ">
<subfield code="c">Université de Neuchâtel / Faculté de droit</subfield>
<subfield code="t">http://www.rcassurances.ch/</subfield>
<subfield code="g">2020//Mai/1-9</subfield>
<subfield code="d">Université de Neuchâtel / Faculté de droit</subfield>
</datafield>
```

**Comment by sebastiendeleze** [comment]
Ok, I understand, but the question is: Users can provide a full date for this field, that becomes something like this for the first part of 773$g?: 

```
<datafield tag="773" ind1=" " ind2=" ">
<subfield code="c">Université de Neuchâtel / Faculté de droit</subfield>
<subfield code="t">http://www.rcassurances.ch/</subfield>
<subfield code="g">2020-01-01///1-9</subfield>
<subfield code="d">Université de Neuchâtel / Faculté de droit</subfield>
</datafield>
```

**Comment by pronguen** [comment]
Since there is already a field "Document date" (provisionActivity > startDate), it is not useful to enter the full date again in numberingYear. What is more, numberingYear is used to sort all articles inside a journal, by year/volume/issue/page. The precise date is not wanted.

**Comment by sebastiendeleze** [comment]
👍 Thanks!
