### ISSUE TITLE
Change behavior of submission form, when document type is changed.

### ISSUE THREAD

**Issue by sebastiendeleze** [rero/sonar-ui#68]
Currently, the form corresponds to postprint document type.

In a first step hide or show publication depending document type is a part of a publication or not.

**Comment by sebastiendeleze** [comment]
@pronguen In the document *conv_rerodoc.ods*, you mention some document types (coar:c_beb9, coar:c_6670, ...) that are not part of the other document *doc_typology_mapping.csv*. Could you provide me the full list of document types, please?

**Comment by pronguen** [comment]
@sebastiendeleze Yes, there are below:

    1. book (coar:c_2f33)
    2. book part (coar:c_3248)
    3. conference object (coar:c_c94f)
        ◦ conference paper (default) (coar:c_5794)
        ◦ conference paper not in proceedings (coar:c_18cp)
        ◦ conference poster (coar:c_6670)
        ◦ conference poster not in proceedings (coar:c_18co)
        ◦ conference proceedings (coar:c_f744)
    4. dataset (coar:c_ddb1)
    5. contribution to journal (coar:c_3e5a)
        ◦ data paper (coar:c_beb9)
        ◦ journal article (default) (coar:c_6501)
        ◦ newspaper article (coar:c_998f)
        ◦ review article (coar:c_dcae04bc)
    6. lecture (coar:c_8544)
    7. non-textual object1
        ◦ moving image (coar:c_8a7e)
        ◦ still image (coar:c_ecc8)
        ◦ cartographic material (coar:c_12cc)
        ◦ sound (coar:c_18cc)
        ◦ musical notation (coar:c_18cw)
        ◦ software (coar:c_5ce6)
    8. patent (coar:c_15cd)
    9. periodical (coar:c_2659)
        ◦ journal (coar:c_0640)
        ◦ magazine (coar:c_2cd9)
        ◦ newspaper (coar:c_2fe3)
    10. preprint (coar:c_816b)
    11. report (coar:c_93fc)
        ◦ internal report (coar:c_18ww)
        ◦ memorandum (coar:c_18wz)
        ◦ other type of report (coar:c_18wq)
        ◦ policy report (coar:c_186u)
        ◦ project deliverable (coar:c_18op)
        ◦ report part (coar:c_ba1f)
        ◦ report to funding agency (coar:c_18hj)
        ◦ research report (default) (coar:c_18ws)
        ◦ technical report (coar:c_18gh)
    12. thesis (coar:c_46ec)2
        ◦ bachelor thesis (coar:c_7a1f)
        ◦ doctoral thesis (coar:c_db06)
        ◦ master thesis (coar:c_bdcc)
        ◦ habilitation thesis*
        ◦ advanced studies thesis*
        ◦ other*
    13. working paper (coar:c_8042)
    14. other (coar:c_1843)
